Use `sha256` instead of `sha1`
```
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ryfow/homebrew-phabricator/arcanist.rb
Calling Resource#sha1 is disabled!
Use Resource#sha256 instead.
```